[tool.poetry]
name = "pylib"
version = "0.1.0"
description = ""
authors = ["Ashish Arora <arora.ashish@siemens.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
